# Generated by Django 3.1.7 on 2021-05-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('about', models.TextField()),
                ('active', models.CharField(max_length=3)),
                ('age', models.IntegerField()),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prof', to='login_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_msg', to='login_app.user')),
                ('liked_by', models.ManyToManyField(related_name='like_message', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='InfuseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('desc', models.TextField()),
                ('bleed', models.CharField(max_length=3)),
                ('dose_amount', models.CharField(max_length=100)),
                ('dose_onHand', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='login_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='login_app.user')),
                ('msg_kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgboard_comments', to='Infusion.messageboard')),
            ],
        ),
    ]
